// angular/layout/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './header/header.component';
import { FooterComponent } from './footer/footer.component';
import { SidebarComponent } from './sidebar/sidebar.component';
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    RouterOutlet,
    HeaderComponent,
    FooterComponent,
    SidebarComponent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'layout';
}

<div class="app-container">
  <app-header></app-header>
  <div class="content-wrapper">
    <app-sidebar></app-sidebar>
    <div class="main-content">
      <h1>Main Content Area</h1>
      <p>This is where your main content will go.</p>
    </div>
  </div>
  <app-footer></app-footer>
</div>

// react/layout/src/App.js
import "./App.css";
import Header from "./components/Header";
import SideBar from "./components/SideBar";
import Footer from "./components/Footer";
function App() {
  return (
    <div className="app-container">
      <Header />
      <div className="content-wrapper">
        <SideBar />
        <main
          style={{
            backgroundColor: "lime",
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
          className="main-content"
        >
          <h1>Main Content Area</h1>
          <p>This is where your main content will go.</p>
        </main>
      </div>
      <Footer />
    </div>
  );
}

export default App;
